In [4]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt

In [10]:
salesData = pd.read_csv("sample_data/sales_data.csv", parse_dates=["Date"])

In [11]:
salesData.head()

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23.0,45.0,120.0,1366.0,1035.0,2401.0
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20.0,45.0,120.0,1188.0,900.0,2088.0
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4.0,45.0,120.0,238.0,180.0,418.0

In [12]:
salesData.shape

(62205, 18)

In [13]:
print(salesData.iloc[9])

Date                2016-02-22 00:00:00
Day                                  22
Month                          February
Year                               2016
Customer_Age                         35
Age_Group                Adults (35-64)
Customer_Gender                       M
Country                       Australia
State                          Victoria
Product_Category            Accessories
Sub_Category                 Bike Racks
Product             Hitch Rack - 4-Bike
Order_Quantity                     21.0
Unit_Cost                          45.0
Unit_Price                        120.0
Profit                           1046.0
Cost                              945.0
Revenue                          1991.0
Name: 9, dtype: object

In [14]:
salesData.describe()

,Date,Day,Year,Customer_Age,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
count,62205,62205.000000,62205.000000,62205.000000,62204.000000,62204.000000,62204.000000,62204.000000,62204.000000,62204.000000
mean,2014-11-28 14:35:34.477935872,15.610562,2014.417040,36.085781,12.114285,260.041444,457.305543,313.558228,492.419812,805.978040
min,2011-01-01 00:00:00,1.000000,2011.000000,2.000000,1.000000,2.000000,5.000000,-30.000000,2.000000,4.000000
25%,2013-12-25 00:00:00,8.000000,2013.000000,28.000000,2.000000,4.000000,9.000000,42.000000,48.000000,103.000000
50%,2014-06-27 00:00:00,16.000000,2014.000000,35.000000,11.000000,13.000000,35.000000,129.000000,153.000000,305.000000
75%,2016-01-11 00:00:00,23.000000,2016.000000,43.000000,20.000000,42.000000,54.000000,383.000000,420.000000,830.000000
max,2016-07-31 00:00:00,31.000000,2016.000000,87.000000,32.000000,2171.000000,3578.000000,5638.000000,8684.000000,14169.000000
std,NaN,8.784415,1.258967,10.868314,9.481290,544.561738,941.462451,473.621349,865.715619,1309.384767

In [16]:
salesData['Unit_Cost'].describe()

count    62204.000000
mean       260.041444
std        544.561738
min          2.000000
25%          4.000000
50%         13.000000
75%         42.000000
max       2171.000000
Name: Unit_Cost, dtype: float64

In [17]:
salesData['Unit_Cost'].mean()

np.float64(260.0414442801106)